### ISSUE TITLE
when i try to run the server

### ISSUE THREAD

**Issue by yorivor** [adrigardi90/video-chat#25]
npm run run:server

> video-chat@0.1.0 run:server C:\git\video-chat
> node ./server/index.js

Server Listening on port 3000
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
Emitted 'error' event at:
    at RedisClient.onError (C:\git\video-chat\node_modules\socket.io-redis\index.js:118:12)
    at RedisClient.emit (events.js:202:15)
    at RedisClient.on_error (C:\git\video-chat\node_modules\redis\index.js:406:14)
    at Socket.<anonymous> (C:\git\video-chat\node_modules\redis\index.js:279:14)
    at Socket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video-chat@0.1.0 run:server: `node ./server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the video-chat@0.1.0 run:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rovi.cruz.PH\AppData\Roaming\npm-cache\_logs\2020-06-26T05_40_38_619Z-debug.log

**Comment by adrigardi90** [comment]
Do you have redis up and running in your local? Starting up the app via `npm run run:server` just run the node process. Try to run it via docker-compose to check whether you still get the same issue.

**Comment by mpena2099** [comment]
Exactly the same error here. :-/

**Comment by mpena2099** [comment]
After install "redis":

$ npm run run:server
I see "Cannot GET /" on http://localhost:3000/

$ npm run serve
I got the same "Something went wrong" error as in #28 .

**Comment by adrigardi90** [comment]
Bear in mind `npm run run:server` and `npm run server` just run the node process assuming redis is already up and running.

Check this out to get it running. 
https://medium.com/@petehouston/install-and-config-redis-on-mac-os-x-via-homebrew-eb8df9a4f298

**Comment by mpena2099** [comment]
> Bear in mind `npm run run:server` and `npm run server` just run the node process assuming redis is already up and running.
> 
> Check this out to get it running.
> https://medium.com/@petehouston/install-and-config-redis-on-mac-os-x-via-homebrew-eb8df9a4f298

Thanks @adrigardi90 , that probably was my mistake. At the moment the only thing that still doesn't work is the video, when I try to access the server by local IP (192.168.0.43) and not by localhost, as I indicated in issue #10 .

**Comment by alfonsoIST** [comment]
@mpena2099 I had the same problem you mentioned with the video and solved it using https.
